name: jikan
description: Dart wrapper for the Jikan API, the unofficial API for MyAnimeList's website.
version: 0.0.2
author: Sandro Marques <sandro123iv@gmail.com>
homepage: https://github.com/SandroHc/jikan-dart

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  http: ^0.12.0
  json_annotation: ^2.0.0

dev_dependencies:
  test: ^1.3.3

  build_verify: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
